WebAPI/ConsumeAPI/Models/ErrorViewModel.cs
namespace ConsumeAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAPI/ConsumeAPI/Controllers/ConsumeController.cs
using Microsoft.AspNetCore.Mvc;
using WebAPI.Web.Models.VillaModel;
using System.Text.Json.Serialization;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace ConsumeAPI.Controllers
{
    public class ConsumeController : Controller
    {
        private string localURL = "https://localhost:44340";
        public IActionResult Index()
        {
            List<House> data = new List<House>();
            try
            {
                using (HttpClient client = new HttpClient()) {
                    client.BaseAddress = new Uri(localURL);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage message = client.GetAsync("/api/House/GetAll").Result;
                    client.Dispose();
                    if (message.IsSuccessStatusCode)
                    {
                        string stringData=message.Content.ReadAsStringAsync().Result;   
                        data=JsonConvert.DeserializeObject<List<House>>(stringData);
                    }
                    else
                    {
                        TempData["error"] =$"{message.ReasonPhrase}";
                    }
                }
            }
            catch(Exception ex)
            {
                TempData["exception"]=ex.Message;
            }
            return View(data);
        }


    }
}

WebAPI/ConsumeAPI/Controllers/HomeController.cs
using ConsumeAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ConsumeAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAPI/ConsumeAPI/Views/Consume/Index.cshtml
@model IEnumerable<WebAPI.Web.Models.VillaModel.House>

    <div class="container">
        <div class="row">
            <div class="col-10 offset-1">
                <table class="table table-bordered table-striped table-hover">
                    <thead class="bg-dark text-light text-center">
                        <tr>
                            <th>Name</th>
                            <th>Details</th>
                            <th>Rate</th>
                            <th>Sqrt</th>
                            <th>Occupancy</th>
                            <th>Amenity</th>
                            <th>Created Date</th>
                            <th>Updated date</th>
                            <th>Images</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                    @if (Model.Count() > 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.Details</td>
                                <td>@item.Rate</td>
                                <td>@item.Sqrt</td>
                                <td>@item.Occupancy</td>
                                <td>@item.Amenity</td>
                                <td>@item.Createddate</td>
                                <td>@item.UpdatedDate</td>
                                <td>@item.ImageUrl</td>
                            </tr>
                        }
                    }
                </tbody>
                </table>
            </div>

        </div>
    </div>

WebAPI/ConsumeAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAPI/ConsumeAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsumeAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConsumeAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConsumeAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consume" asp-action="Index">House List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ConsumeAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>